pipeline:

  - step: ingest
    source:
      format: kafka
      options:
        kafka.bootstrap.servers: KAFKA_BOOTSTRAP_SERVER
        subscribe: KAFKA_TOPIC
        startingOffsets: latest

    transformation:
      schema: wikimedia-recent-change

    destination:
      format: parquet
      outputMode: append
      options:
        path: data/bronze/wikimedia-recent-change


  - step: transform
    source:
      format: parquet
      path: data/bronze/wikimedia-recent-change
      schema: wikimedia-recent-change

    transformation:
      schema: wikimedia-recent-change

    destination:
      format: parquet
      outputMode: append
      options:
        path: data/silver/wikimedia-recent-change
        checkpointLocation: path-to-checkpoint
