# Prometheus Local Configuration
global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'kafka-broker-1'
    static_configs:
      - targets: ['kafka:8080']
        labels:
          kubernetes_pod_name: 'kafka-broker-1'
